### ISSUE TITLE
登录功能

### ISSUE THREAD

**Issue by Jxells** [zhuweiyou/chatgpt-api#10]
api登录还能修复下吗

**Comment by zhuweiyou** [comment]
之前调用的这两个项目, 
https://github.com/acheong08/OpenAIAuth 
https://github.com/ericlewis/openai-authenticator
他们都不更新了

**Comment by zhuweiyou** [comment]
OpenAIAuth 作者好像在更新了,等他更了, 我这边集成进来

**Comment by zhuweiyou** [comment]
已支持
