### ISSUE TITLE
返回回答很慢怎么回事？

### ISSUE THREAD

**Issue by nanxun1991** [zhuweiyou/chatgpt-api#11]
在官网登录的话回复很快  用这种方式的话回答很慢是哪里的问题？

**Comment by zhuweiyou** [comment]
在网页玩的时候,是手动cloudflare人机验证的,
这种方式是程序帮你过人机验证的,内部会走一个代理服务.

另一个原因是网页版是stream流式输出内容,一个一个吐的,所以给你感觉很快. 
而这种方式是要等所有内容都吐了才返回.
