### ISSUE TITLE
调用接口好像变了

### ISSUE THREAD

**Issue by jindc123** [zhuweiyou/chatgpt-api#12]
我昨天还能调用，今天就有错了
b'{"message":"fetch failed"}'
{"message":"fetch failed"}
{'message': 'fetch failed'}

**Comment by zhuweiyou** [comment]
确保token没过期的情况下 ,
调用 `send_message` 加个参数 `reverse_proxy: 'https://api.pawan.krd/backend-api/conversation'` 试试

**Comment by jindc123** [comment]
我是docker方式部署的，你说的加个参数 reverse_proxy: 'https://api.pawan.krd/backend-api/conversation' 该怎么加啊

**Comment by zhuweiyou** [comment]
你调用的时候 POST加,  docker那边不用动

文档我更新了

**Comment by jindc123** [comment]
reverse_proxy: 'https://api.pawan.krd/backend-api/conversation'。已经好了。谢谢大佬！
