### ISSUE TITLE
一直报错： {"message":"invalid [access_token] or [prompt]"}

### ISSUE THREAD

**Issue by qiyongzhanghao** [zhuweiyou/chatgpt-api#16]
我使用这个一直报错：
 {"message":"invalid [access_token] or [prompt]"}
access_token 是从浏览器获取的，请问有可能是什么原因？

**Comment by zhuweiyou** [comment]
你的代码贴上来看看，是post body格式不正确，请参考readme.md中的postman截图的方式



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月8日(周六) 上午7:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhuweiyou/chatgpt-api] 一直报错： {"message":"invalid [access_token] or [prompt]"} (Issue #16)




 
我使用这个一直报错：
 {"message":"invalid [access_token] or [prompt]"}
 access_token 是从浏览器获取的，有可能是什么原因？

**Comment by qiyongzhanghao** [comment]
感谢回复~ 好像 form-date 的报错是 {"message":"invalid [access_token] or [prompt]"}
x-www-form-urlencoded 的报错是："message": "fetch failed"
![image](https://user-images.githubusercontent.com/18416461/230696487-3aaea5e9-924e-4e0d-aa38-ea87cd3eec2f.png)
![image](https://user-images.githubusercontent.com/18416461/230696523-3ce6365d-8f2b-4861-84b2-2cedb191680f.png)

另外我用了以下两种代码测试，报错是： {"message":"invalid [access_token] or [prompt]"}
```
import axios from 'axios'
const res = await axios.post('http://127.0.0.1:3000/send_message', {
    access_token: "xxxxxxxxxxxxxxxxxxxx",
    prompt: "你好，你会说中文吗"
  });
  console.log(res.data);
```

```
const http = require('http');
const postData = JSON.stringify({
  access_token: "xxxxxxxxxxxxxxxxxx",
  prompt: "你好，你会说中文吗"
});
const options = {
  hostname: '127.0.0.1',
  port: 3000,
  path: '/send_message',
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(postData)
  }
};
const req = http.request(options, (res) => {
  console.log(`状态码: ${res.statusCode}`);
  res.on('data', (chunk) => {
    console.log(`响应主体: ${chunk}`);
  });
  res.on('end', () => {
    console.log('响应中已无数据。');
  });
});
req.on('error', (e) => {
  console.error(`请求遇到问题: ${e.message}`);
});
req.write(postData);
req.end();
```

**Comment by zhuweiyou** [comment]
用 `x-www-form-urlencoded` 格式, POST多带一个参数 reverse_proxy: 'https://api.pawan.krd/backend-api/conversation'

**Comment by qiyongzhanghao** [comment]
> 用 `x-www-form-urlencoded` 格式, POST多带一个参数 reverse_proxy: 'https://api.pawan.krd/backend-api/conversation'

![image](https://user-images.githubusercontent.com/18416461/230696772-147c2645-18fe-4695-a82f-5d1e0756c962.png)
感谢！！可以了！！

**Comment by zhuweiyou** [comment]
我稍后更新一版代码,默认成这个proxy

**Comment by qiyongzhanghao** [comment]
感谢，辛苦了！❤

**Comment by XR-stb** [comment]
> > 用 `x-www-form-urlencoded` 格式, POST多带一个参数 reverse_proxy: 'https://api.pawan.krd/backend-api/conversation'
> 
> ![image](https://user-images.githubusercontent.com/18416461/230696772-147c2645-18fe-4695-a82f-5d1e0756c962.png) 感谢！！可以了！！

![image](https://github.com/zhuweiyou/chatgpt-api/assets/56108982/e5169913-4792-4611-a166-9c82e1254904)
好奇怪，为什么我不行

**Comment by dzwzqlx** [comment]
> > > 用 `x-www-form-urlencoded` 格式, POST多带一个参数 reverse_proxy: 'https://api.pawan.krd/backend-api/conversation'
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/18416461/230696772-147c2645-18fe-4695-a82f-5d1e0756c962.png) 感谢！！可以了！！
> 
> ![image](https://user-images.githubusercontent.com/56108982/246306065-e5169913-4792-4611-a166-9c82e1254904.png) 好奇怪，为什么我不行

你换这个反代服务器试试：https://ai.fakeopen.com/api/conversation
第三方的反代服务器不太稳定，可能随时需要换换
