### ISSUE TITLE
plus会员怎么使用gpt-4的方法

### ISSUE THREAD

**Issue by naihetxi** [zhuweiyou/chatgpt-api#18]

**Comment by zhuweiyou** [comment]
https://github.com/zhuweiyou/chatgpt-api/blob/e6deac0df27b73d36d687c24cc76f494ac396462/send_message.mjs#L18

因为我手上没有plus账号, 你可以在这里加一个参数 model: 'gpt-4' , 应该有效.

如果测试OK,我更新一下POST参数

**Comment by naihetxi** [comment]
好的 我加一下试试 谢谢

**Comment by naihetxi** [comment]
![image](https://user-images.githubusercontent.com/16144446/231634400-d43844a5-0185-4b52-9dff-3337c9538ef4.png)
![image](https://user-images.githubusercontent.com/16144446/231634618-471ba4ff-1d3b-44ae-a4c4-0cb10a672676.png)
![image](https://user-images.githubusercontent.com/16144446/231635815-ee303354-1cec-4b4a-b40c-001e4766309c.png)
加单引号后可以 
![image](https://user-images.githubusercontent.com/16144446/231635929-ab62e5ab-dfd1-4f4b-b88e-2cd47b3b1f94.png)
<img width="938" alt="image" src="https://user-images.githubusercontent.com/16144446/231635964-adea89e5-218f-45bf-bba8-a9bc60a575b2.png">

**Comment by zhuweiyou** [comment]
你这样只能证明可以传入, 不能代表切换了 `gpt-4`. 你可以问一下它是3.5还是4 之类的.

**Comment by naihetxi** [comment]
我在postman请求了一个你好，然后登录网页去查看 页面显示是使用的4去回复的

**Comment by zhuweiyou** [comment]
那就OK?

**Comment by naihetxi** [comment]
![image](https://user-images.githubusercontent.com/16144446/231637922-d3a25d08-ede9-4856-904c-0faf4b8e4cc6.png)

OK的 我又验证了下

**Comment by zhuweiyou** [comment]
多谢你测试,我晚点代码更新一下,把model作为post传入

**Comment by zhuweiyou** [comment]
#20 已支持
