### ISSUE TITLE
No bypass servers available

### ISSUE THREAD

**Issue by datouchaoshuai** [zhuweiyou/chatgpt-api#21]
报错是为什么
{
	"message": "ChatGPT error 500: {\"error\":\"No bypass servers available. please wait 5 mins and try again.\"}"
}

**Comment by zhuweiyou** [comment]
https://github.com/zhuweiyou/chatgpt-api#%E7%AC%AC%E4%BA%8C%E6%AD%A5-%E5%90%91-chatgpt-%E6%8F%90%E9%97%AE

看这里, 尝试更换为其它的 reverse_proxy

**Comment by datouchaoshuai** [comment]
> 

三个都试过了，都报了不同的错误

**Comment by bigBoyooooooo** [comment]
https://github.com/zhuweiyou/chatgpt-api/issues/21#issuecomment-1510602888

> https://github.com/zhuweiyou/chatgpt-api#%E7%AC%AC%E4%BA%8C%E6%AD%A5-%E5%90%91-chatgpt-%E6%8F%90%E9%97%AE
> 
> 看这里, 尝试更换为其它的 reverse_proxy

This is useful to me, thank you

**Comment by datouchaoshuai** [comment]
![image](https://user-images.githubusercontent.com/101850763/232366225-76934669-c867-4239-b529-5a6acc18a5f5.png)
![image](https://user-images.githubusercontent.com/101850763/232366379-60addabf-8641-47e4-b235-9d9cfaf72a9e.png)

**Comment by zhuweiyou** [comment]
那个被和谐了, 换成 reverse_proxy: `https://ai.fakeopen.com/api/conversation`

**Comment by zhuweiyou** [comment]
![image](https://user-images.githubusercontent.com/8413791/232705152-bb280669-8352-4924-9b47-fb61a396f481.png)
