### ISSUE TITLE
Interface problem: Always unable to send a message, prompting "ChatGPT timed out waiting for response"

### ISSUE THREAD

**Issue by XiaomaiTX** [zhuweiyou/chatgpt-api#24]
I set up the chat-api service using docker on a server that has normal access to the OpenAI service, and used nginx to reverse proxy it out, but I can't send messages regardless of whether I set a timeout or not, my OpenAI account and accessToken are fine, and it works fine on other services
![60s](https://user-images.githubusercontent.com/59403296/234245095-453592b6-74b1-487b-a18e-b394947ce508.png)
![No timeout is set](https://user-images.githubusercontent.com/59403296/234245144-4ae79141-b1c7-4a40-8fcb-ea8d9768c520.png)
![docker container logs](https://user-images.githubusercontent.com/59403296/234245171-80828e25-965c-4aa3-9af5-a2a721b97a9f.png)

**Comment by zhuweiyou** [comment]
超时时间是毫秒的,一般不用传

昨天还是正常的
我刚试了一下 reverse_proxy 今天确实出了问题, 因为是别人的服务, 等他修复后我再更新

**Comment by XiaomaiTX** [comment]
建议可以使用这里的代理地址
https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy

**Comment by zhuweiyou** [comment]
现在用的就是这里的.

**Comment by XiaomaiTX** [comment]
我在chat-web中使用这个代理地址是正常的哦，不知道你这边是哪里出了问题
![图片](https://user-images.githubusercontent.com/59403296/234252590-0156db9a-d259-42b4-bb97-245c7814cead.png)
![图片](https://user-images.githubusercontent.com/59403296/234252635-6a48658e-be2b-4c9e-a82d-3eeb26d0c840.png)

**Comment by zhuweiyou** [comment]
我刚试了又正常了
![image](https://user-images.githubusercontent.com/8413791/234253448-7e086563-f107-4b61-8864-e4ac8921363b.png)

他服务抽风吧, 或者他修好了

**Comment by XiaomaiTX** [comment]
好的，我再试试吧
