### ISSUE TITLE
不用 API key，但是要账号 (*/ω＼*)

### ISSUE THREAD

**Issue by izkizk8** [zhuweiyou/chatgpt-api#4]
账号和 api key token 是一样的吧

**Comment by zhuweiyou** [comment]
不一样, api key会消耗额度. 
而帐号只是用来登录而已 (就是正常玩的那个网页版)

**Comment by izkizk8** [comment]
> 不一样, api key会消耗额度. 
> 而帐号只是用来登录而已 (就是正常玩的那个网页版)

好的，了解了，感谢解答~

**Comment by Jxells** [comment]
requests.exceptions.SSLError: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)

**Comment by zhuweiyou** [comment]
> requests.exceptions.SSLError: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)

获取token失败,  不确定是不是昨天更新gpt4之后出的问题. 
临时方案: 手动打开网页,看network中session请求,有access_token返回,直接取来用.

![WX20230315-201228@2x](https://user-images.githubusercontent.com/8413791/225305658-188ec53c-c3ee-4ec6-9306-9ff9ce2c94af.png)
