### ISSUE TITLE
docker 安装了，怎么进docker,怎么使用docker来调用?

### ISSUE THREAD

**Issue by kintzhao** [zhuweiyou/chatgpt-api#6]
int@kint:~/gpt/chatgpt-api$ ls
catch_error.mjs  index.mjs     package-lock.json  requirements.txt
dockerfile       package.json  readme.md          send_message.mjs

kint@kint:~/gpt/chatgpt-api$ docker build -f  ./dockerfile .
[+] Building 30.4s (4/10)                                                                                                                                      
 => [internal] load build definition from dockerfile                                                                                                      0.0s
 => => transferring dockerfile: 307B                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                         0.0s
[+] Building 30.5s (4/10)                                                                                                                                      
 => [internal] load metadata for docker.io/library/node:18-alpine                                                                                         9.4s
 => [1/6] FROM docker.io/library/node:18-alpine@sha256:ffc770cdc09c9e83cccd99d663bb6ed56cfaa1bab94baf1b12b626aebeca9c10                                  21.1s
 => => resolve docker.io/library/node:18-alpine@sha256:ffc770cdc09c9e83cccd99d663bb6ed56cfaa1bab94baf1b12b626aebeca9c10                                   0.0s
[+] Building 51.0s (11/11) FINISHED                                                                                                                            
 => [internal] load build definition from dockerfile                                                                                                      0.0s
 => => transferring dockerfile: 307B                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                         0.0s
 => => transferring context: 82B                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/node:18-alpine                                                                                         9.4s
 => [1/6] FROM docker.io/library/node:18-alpine@sha256:ffc770cdc09c9e83cccd99d663bb6ed56cfaa1bab94baf1b12b626aebeca9c10                                  37.0s
 => => resolve docker.io/library/node:18-alpine@sha256:ffc770cdc09c9e83cccd99d663bb6ed56cfaa1bab94baf1b12b626aebeca9c10                                   0.0s
 => => sha256:63b65145d645c1250c391b2d16ebe53b3747c295ca8ba2fcb6b0cf064a4dc21c 3.37MB / 3.37MB                                                           34.2s
 => => sha256:f41005eb563ce84e6c742a787d6a598fde273c134e94c90acc6115853a7f8315 47.54MB / 47.54MB                                                          4.0s 
 => => sha256:69dcb013f10fed3864b0f9915d6721b09f0c6717e5452ee96e04fde6082322a7 2.35MB / 2.35MB                                                           36.9s 
 => => sha256:ffc770cdc09c9e83cccd99d663bb6ed56cfaa1bab94baf1b12b626aebeca9c10 1.43kB / 1.43kB                                                            0.0s 
 => => sha256:19eaf41f3b8c2ac2f609ac8103f9246a6a6d46716cdbe49103fdb116e55ff0cc 1.16kB / 1.16kB                                                            0.0s 
 => => sha256:f520ad35ba68f1ed1301a5eda87eaa722e468a9fc3a179868a035dc4c5dddaef 6.48kB / 6.48kB                                                            0.0s
 => => sha256:00a00d31565028f3c00c64959dafe4587320e8c99a39982ccda8a8a9ccef7123 449B / 449B                                                                4.3s
 => => extracting sha256:63b65145d645c1250c391b2d16ebe53b3747c295ca8ba2fcb6b0cf064a4dc21c                                                                 0.1s
 => => extracting sha256:f41005eb563ce84e6c742a787d6a598fde273c134e94c90acc6115853a7f8315                                                                 0.7s
 => => extracting sha256:69dcb013f10fed3864b0f9915d6721b09f0c6717e5452ee96e04fde6082322a7                                                                 0.0s
 => => extracting sha256:00a00d31565028f3c00c64959dafe4587320e8c99a39982ccda8a8a9ccef7123                                                                 0.0s
 => [internal] load build context                                                                                                                         0.0s
 => => transferring context: 402.88kB                                                                                                                     0.0s
 => [2/6] RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories                                                      0.3s
 => [3/6] RUN apk add -U tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && apk del tzdata                                                  1.8s
 => [4/6] WORKDIR /app                                                                                                                                    0.0s
 => [5/6] COPY . .                                                                                                                                        0.0s
 => [6/6] RUN npm install                                                                                                                                 2.3s
 => exporting to image                                                                                                                                    0.2s
 => => exporting layers                                                                                                                                   0.2s
 => => writing image sha256:fad5e3eb6843a30083dc787d8842f6fb5a929e863fa07d2ee727a1f71e5eb365                                                              0.0s

-------------------------------------------------------

kint@kint:~/gpt/chatgpt-api$ docker images 
REPOSITORY    TAG                      IMAGE ID       CREATED         SIZE
<none>        <none>                   fad5e3eb6843   5 seconds ago   209MB
 
kint@kint:~/gpt/chatgpt-api$ docker run -d -p 3000:3000 fad5e3eb6843 
bfeb68b0efd5209b6f09bac14d881978d9107e7c16f094e803796e8594bde1a8

**Comment by zhuweiyou** [comment]
```bash
docker run -d -p 3000:3000 zhuweiyou/chatgpt-api:20230317
```
这样就可以了, 不用你自己build

用法看readme.md

**Comment by 9E307** [comment]
搞半天我才反应过来这个是没有web ui的？docker反而只是一个转发后端。我最后还要用一个post工具来调试使用吗？

**Comment by 9E307** [comment]
> ```shell
> docker run -d -p 3000:3000 zhuweiyou/chatgpt-api:20230317
> ```
> 
> 这样就可以了, 不用你自己build
> 
> 用法看readme.md

搞半天我才反应过来这个是没有web ui的？docker反而只是一个转发后端。我最后还要用一个post工具来调试使用吗

**Comment by zhuweiyou** [comment]
> 搞半天我才反应过来这个是没有web ui的？docker反而只是一个转发后端。我最后还要用一个post工具来调试使用吗

是的没有, 本来我是用来QQ/WX机器人调用的,如果你要的是ui应该找这种项目 https://github.com/ddiu8081/chatgpt-demo
