### ISSUE TITLE
npm启动不了  卡住不动了

### ISSUE THREAD

**Issue by nanxun1991** [zhuweiyou/chatgpt-api#9]
npm和cnpm都试了  都是卡在这里不动了
![image](https://user-images.githubusercontent.com/13490885/226588149-d0a28871-6bdb-4032-bf7f-bc58b957bee4.png)

**Comment by zhuweiyou** [comment]
这样就已经成功了











发自我的iPhone

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月21日(周二) 晚上7:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhuweiyou/chatgpt-api] npm启动不了  卡住不动了 (Issue #9)




 
npm和cnpm都试了  都是卡在这里不动了

**Comment by nanxun1991** [comment]
> 这样就已经成功了 发自我的iPhone
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年3月21日(周二) 晚上7:06 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [zhuweiyou/chatgpt-api] npm启动不了 卡住不动了 (Issue #9) npm和cnpm都试了 都是卡在这里不动了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;



> 这样就已经成功了 发自我的iPhone
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年3月21日(周二) 晚上7:06 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [zhuweiyou/chatgpt-api] npm启动不了 卡住不动了 (Issue #9) npm和cnpm都试了 都是卡在这里不动了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

谢谢  可以用啦
